name: book_my_shot
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  auto_route: ^2.2.0
  bloc: ^7.0.0
  flutter_neumorphic_null_safety: ^3.2.0
  hive: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3

flutter:
  uses-material-design: true
