name: book_my_shot
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # * Routing [https://pub.dev/packages/auto_route]
  auto_route: ^2.2.0
  
  # * State Management [https://pub.dev/packages/bloc]
  bloc: ^7.0.0
  
  # * HTTP Library [https://pub.dev/packages/dio]
  dio: ^4.0.0
  
  # * Firebase Core [https://pub.dev/packages/firebase_core]
  firebase_core: ^1.1.1
  
  # * Neumorphic UI [https://pub.dev/packages/flutter_neumorphic_null_safety]
  flutter_neumorphic_null_safety: ^3.2.0

  # * SVG Rendering [https://pub.dev/packages/flutter_svg]
  flutter_svg: ^0.22.0

  # * Google Fonts [https://pub.dev/packages/google_fonts]
  google_fonts: ^2.0.0
  
  # * Local Storage [https://pub.dev/packages/hive]
  hive: ^2.0.4
  
  # * Directory on target [https://pub.dev/packages/path_provider]
  path_provider: ^2.0.1
  
  # * SMS read [https://pub.dev/packages/telephony]
  telephony: ^0.1.3
  mobile_number: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - res/svg/splash/
    - res/svg/onboarding/welcome/
    - res/svg/
